/**
 * Air brake system with reservoir dynamics and thermal fade.
 *
 * Three behaviours here are specific to heavy vehicles and all of them change
 * how the rig must be driven:
 *
 *  - Application lag. Air takes time to travel to the trailer, so a long
 *    combination starts braking from the front and pushes from the back. That
 *    lag is the trailer-swing mechanism during a panic stop.
 *
 *  - Reservoir depletion. Repeated hard applications ("fanning" the brakes)
 *    outrun the compressor. Below ~60 psi warning, below ~35 psi the spring
 *    brakes drop and the rig stops wherever it is.
 *
 *  - Thermal fade. Drum brakes hauling 200,000 lb down a grade heat quickly and
 *    lose a large fraction of their torque. This is why the compression brake
 *    and a low gear -- not the pedal -- are how a loaded rig descends.
 */

const AMBIENT_C = 20;

export class BrakeGroup {
  /**
   * @param maxTorque peak torque per wheel at full application, cold, Nm
   * @param thermalMass larger = slower to heat and cool
   */
  constructor({ maxTorque = 14000, thermalMass = 26000, coolingArea = 62, lag = 0.18 } = {}) {
    this.maxTorque = maxTorque;
    this.thermalMass = thermalMass;
    this.coolingArea = coolingArea;
    this.lag = lag;

    this.applied = 0;      // actual applied fraction after lag
    this.tempC = AMBIENT_C;
    this.fade = 1;         // multiplier on torque, 1 = no fade
  }

  /**
   * @param dt        seconds
   * @param demand    0..1 commanded application
   * @param supplyPsi available air pressure
   * @param airspeed  m/s, drives convective cooling
   */
  update(dt, demand, supplyPsi, airspeed) {
    // Below ~35 psi there is not enough air to hold the spring brakes off, so
    // they apply fully and cannot be released.
    if (supplyPsi < 35) {
      this.applied = 1;
    } else {
      const authority = Math.min(1, Math.max(0, (supplyPsi - 35) / 55));
      const target = demand * authority;
      this.applied += (target - this.applied) * Math.min(1, dt / this.lag);
    }

    // Fade curve: negligible to ~200C, then falls away steeply. At 500C a drum
    // brake retains roughly a third of its cold torque.
    const t = this.tempC;
    if (t < 200) this.fade = 1;
    else this.fade = Math.max(0.25, 1 - (t - 200) / 430);

    return this.applied;
  }

  /**
   * Adds the heat generated by this wheel's brake and sheds it to the airstream.
   * @param power watts of friction power dissipated at this wheel
   */
  addHeat(dt, power, airspeed) {
    this.tempC += (power * dt) / this.thermalMass;
    const h = this.coolingArea * (1.6 + 0.9 * airspeed); // W/K, forced convection
    this.tempC -= ((this.tempC - AMBIENT_C) * h * dt) / this.thermalMass;
    if (this.tempC < AMBIENT_C) this.tempC = AMBIENT_C;
  }

  /** Torque available at this wheel right now. */
  torque() {
    return this.maxTorque * this.applied * this.fade;
  }
}

export class AirSystem {
  constructor({ reservoirPsi = 120, compressorRate = 9.5, cutIn = 100, cutOut = 125 } = {}) {
    this.psi = reservoirPsi;
    this.compressorRate = compressorRate; // psi per second while loaded
    this.cutIn = cutIn;
    this.cutOut = cutOut;
    this.compressorOn = false;
    this.parkingBrake = true;
    this.lowPressureWarning = false;
  }

  /**
   * @param demand  0..1 service brake application
   * @param engineRpm drives compressor output
   */
  update(dt, demand, engineRpm) {
    // Governor cycles the compressor between cut-in and cut-out.
    if (this.psi <= this.cutIn) this.compressorOn = true;
    if (this.psi >= this.cutOut) this.compressorOn = false;

    if (this.compressorOn) {
      const rpmFactor = Math.min(1.3, engineRpm / 1200);
      this.psi += this.compressorRate * rpmFactor * dt;
    }

    // Each application consumes air. Holding costs far less than repeated
    // applications, which is the whole argument against fanning the brakes.
    this.psi -= demand * 5.2 * dt;
    this.psi = Math.max(0, Math.min(this.cutOut + 5, this.psi));

    this.lowPressureWarning = this.psi < 60;
    if (this.psi < 35) this.parkingBrake = true;
    return this.psi;
  }

  releaseParkingBrake() {
    if (this.psi >= 65) {
      this.parkingBrake = false;
      return true;
    }
    return false;
  }
}
